name       : libcbor
version    : 0.8.0
release    : 1
source     :
    - https://github.com/PJK/libcbor/archive/v0.8.0.tar.gz : 618097166ea4a54499646998ccaa949a5816e6a665cf1d6df383690895217c8b
license    : MIT
component  : programming.library
summary    : CBOR protocol implementation for C
description: |
    libcbor is a C library for parsing and generating CBOR, the general-purpose schema-less binary data format.
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=on
build      : |
    %ninja_build
install    : |
    %ninja_install
