name       : libcbor
version    : 0.10.2
release    : 3
source     :
    - https://github.com/PJK/libcbor/archive/v0.10.2.tar.gz : e75f712215d7b7e5c89ef322a09b701f7159f028b8b48978865725f00f79875b
license    : MIT
component  : system.base
summary    : CBOR protocol implementation for C
builddeps  :
    - cmocka-devel
description: |
    libcbor is a C library for parsing and generating CBOR, the general-purpose schema-less binary data format.
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=on \
                 -DWITH_TESTS=1
build      : |
    %ninja_build
install    : |
    %ninja_install
check     : |
    %ninja_check
